# LEGACY WORKFLOW - Use sync-violations.yml instead
# This workflow is kept as a fallback for the old database-based approach
name: Sync Night Logger Data (Legacy)

on:
  # Disabled automatic triggers - use manual dispatch only
  # repository_dispatch:
  #   types: [night-logger-sync]

  # schedule:
  #   - cron: '0 17 * * *'

  # Allow manual triggering for testing legacy system
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download HSoT database from computer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python sync_nightlogger.py download-hsot-db

    - name: Sync databases and Beeminder
      env:
        BEEMINDER_USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
        BEEMINDER_AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
        BEEMINDER_GOAL_SLUG: ${{ secrets.BEEMINDER_GOAL_SLUG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python sync_nightlogger.py sync

    - name: Commit and push SoT database if updated
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        if [ -f "sot_database.db" ]; then
          git add sot_database.db
          if ! git diff --staged --quiet; then
            git commit -m "$(cat <<'EOF'
        Update SoT database - $(date -u '+%Y-%m-%d %H:%M:%S UTC')

        🤖 Automated sync via GitHub Actions

        Co-Authored-By: Claude <noreply@anthropic.com>
        EOF
        )"
            git push
          else
            echo "No database changes to commit"
          fi
        fi